### ISSUE TITLE
Carrito - mejorando experiencia de usuario

### ISSUE THREAD

**Issue by KatuGT** [SantiagoPuertas4/frontendDonPietro#59]
![image](https://github.com/user-attachments/assets/1e0dc729-08eb-4ca0-9903-dd635af7d3cd)

Al añadir un producto, no tengo un indicador de que efectivamente se agrego ni que cantidad de productos voy agregando

Agreguemos en boton del carrito en tamaño pequeño, la cantidad de productos que el usuario va agregando

**Comment by AnabelaGuillermo** [comment]
¡Gracias por tu observación! Agregado en nav cantidad de items en el carrito. ¡Saludos!
