### ISSUE TITLE
Contraseña - indicar caracteres especiales admitidos

### ISSUE THREAD

**Issue by KatuGT** [SantiagoPuertas4/frontendDonPietro#60]
![image](https://github.com/user-attachments/assets/c135e451-021b-4d8f-8220-7c9363d25c09)

Agreguemos en el mensaje de error o en un mensaje permanente en el formulario los requerimientos y no nos olvidemos de indicar cuales son los caracteres especiales admitidos, que por lo que vi en el codigo son $@$!%*?&

Yo por ejemplo intente agregar un punto "." o un guion "-" y no me permitia crear y no sabia cuales eran los admitidos

**Comment by SantiagoPuertas4** [comment]
Elimine los mensajes de largo de la contraseña y unicamente deje el del regex que especifica el largo, minusculas y caracteres especiales, ademas le agregue al mensaje de error los caracteres permitidos
